cloudstack/urls.py
from django.conf.urls import url

from . import views
#import library to allow caching
from django.views.decorators.cache import cache_page

#specify application name
app_name = 'cloudstack'

#some pages below are cached
urlpatterns = [
    url(r'^$', views.index, name='index'),#default view
    url(r'^domains/$', cache_page(60 * 60)(views.domains), name='domains'),#display domains
    url(r'^latestvms/$', cache_page(60 * 15)(views.latest_VMs), name='latestVMs'),#display VMs created in the last 7 days
    url(r'^monthvms/$', cache_page(60 * 15)(views.month_VMs), name='monthVMs'),#display VMs created in the past one month
    url(r'^search/$', views.search_form, name='search_form'),#display the account search form
    url(r'^vms/(?P<domain_id>.*)/$', cache_page(60 * 15)(views.list_VMs), name='listVMs'),#list all VMs in a domain
    url(r'^domains/(?P<domain_id>.*)/(?P<account_name>.*)/(?P<VM_id>.*)/$', views.VM, name='VM'),#display VM info
    url(r'^domains/(?P<domain_id>.*)/(?P<account_name>.*)/$', cache_page(60 * 15)(views.account), name='account'),#display VMs in an account
    url(r'^domains/(?P<domain_id>.*)/$', cache_page(60 * 15)(views.domain), name='domain'), #display accounts in a domain
]

project2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^cloudstack/', include('cloudstack.urls', namespace='cloudstack')),
]

users/urls.py
"""Defines URL patterns for users"""
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views

urlpatterns = [
   # Login page
   url(r'^login/$', login, {'template_name': 'users/login.html'},
   name='login'),
   url(r'^logout/$', views.logout_view, name='logout'),
   url(r'^register/$', views.register, name='register'),
]

cloudstack/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

cloudstack/forms.py
from django import forms
from choices import *

class SearchForm(forms.Form):
    your_search = forms.CharField(label='Account', max_length=100, required=True)
    domain = forms.ChoiceField(choices = DOMAIN_CHOICES, required=True)

cloudstack/views.py
# Create your views here.

from django.shortcuts import get_object_or_404, render
# import all the necessary classes/libraries
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse

from django.contrib.auth.decorators import login_required

#custom class to allow interaction with the Cloudstack API
from cloud_api import CloudStack

import re
from operator import itemgetter, attrgetter, methodcaller

#custom form class for use in the search accounts view function
from forms import SearchForm

#import constants
from constants import *

#import helper functions called by the view methods below
from helper_functions import *

# create an object of class Cloudstack to allow API calls to be made
api = CloudStack(api_url, apiKey, secret)

#home page
def index(request):
    return render(request, 'cloudstack/index.html')

#view below returns a list of all the domains
@login_required
def domains(request):
    #prepare and make API call
    query = {'listall':'true'}
    result = api.listDomains(query)
    
    #extract total number of VMs from the list of dictionaries returned
    total = result['count']
    #extract a list of the domains
    domains_list = result['domain']
    context = {'total': total, 'domains_list': domains_list}
    
    # pass on context info to the appropriate template for rendering
    return render(request, 'cloudstack/domains.html', context)

#view below returns a list of all acoounts in a domain
@login_required
def domain(request, domain_id):
    #prepare and make API call
    query = {'domainid': domain_id}
    result = api.listAccounts(query)
    
    #extract total number of accounts
    total = result['count']
    #extract a list of accounts
    accounts_list = result['account']
 
    #sort the account names alphabetically using python function sorted
    accounts_list = sored(accounts_list, key=lambda account: account['name'].lower()) 
   
    context = {'total': total, 'domain_id': domain_id, 'accounts_list': accounts_list}
   
    #pass on context info to template for rendering
    return render(request, 'cloudstack/domain.html', context)

#view that returns a list of all virtual machines (if any) in account
@login_required
def account(request, domain_id, account_name):
    #prepare and make API call
    query = {'account': account_name, 'domainid': domain_id}
    result = api.listVirtualMachines(query)
    
    #handle exception in the case there are no VMs
    try:
     #extract total number of VMs and a list of all VMs
     total = result['count']
     VMs_list = result['virtualmachine']
    
     context = {'account': account_name, 'domainid': domain_id, 'total': total, 'VMs_list': VMs_list}
    #pass on context info to template for rendering
    return render(request, 'cloudstack/account.html', context)
   
    except Exception:
    #if there are no VMs pass on total of 0
     total = 0

     context = {'account': account_name, 'domainid': domain_id, 'total': total}
     return render(request, 'cloudstack/account.html', context)

#view that returns VM details
@login_required
def VM(request, domain_id, account_name, VM_id):
    #prepare and make API call
    query = {'id': VM_id }
    result = api.listVirtualMachines(query)
    
   #extract the single virtual machine from the list of dictionaries
    virtual_machine = result['virtualmachine']
    virtual_machine = virtual_machine[0]
    
    #prepare and make API call to extract volumes (disks) corresponding to the VM id
    query2 = { 'listall': 'true', 'virtualmachineid': VM_id}
    result2 = api.listVolumes(query2)
    total = 0

    #catch exception in the event that there are no volumes attached to the VM
    try:
     #extract total number of volumes and a list of volumes 
     total = result2['count']
     volumes_list = result2['volume']
     context = {'account': account_name, 'total': total, 'volumes_list': volumes_list, 'virtual_machine': virtual_machine}
     #pass on info to template for rendering
     return render(request, 'cloudstack/VM.html', context)
 
    except Exception:
     #if there are no volumes pass total as 0
     total = 0
     context = {'account': account_name, 'total': total, 'volumes_list': volumes_list, 'virtual_machine': virtual_machine}
     #pass on info to template
     return render(request, 'cloudstack/VM.html', context)

#view that returns a list of VMs created in the last one week (7 days)
@login_required
def latest_VMs(request):
    #prepare and make API call
    query = {'listall': 'true' }
    result = api.listVirtualMachines(query)
    
    #extract list of virtual machines
    virtual_machines = result['virtualmachine']   
   
    #filter the list based on creation date of the VM
    latest_list = filter(new_VMs, virtual_machines) 
   
    #obtain the length of the filtered list
    total = len(latest_list)
    context = {'latest_list': latest_list, 'total': total}
    #pass on context info to template for rendering
    return render(request, 'cloudstack/latest_VMs.html', context) 

#view that retruns a list of VMs created in the past one month (30 days)
@login_required
def month_VMs(request):
    #prepare and make API call
    query = {'listall': 'true' }
    result = api.listVirtualMachines(query)

    #extract list of virtual machines
    virtual_machines = result['virtualmachine']

    #filter VMs by creation date
    latest_list = filter(monthVMs, virtual_machines)

    #obtain the length of the filtered list
    total = len(latest_list)
    context = {'latest_list': latest_list, 'total': total}
    #pass on context info to template for rendering
    return render(request, 'cloudstack/month_VMs.html', context)   
  
#view to search by full or partial account name if an account exists in a particular domain
@login_required
def search_form(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = SearchForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            #extract data from form
            search_value = form.cleaned_data['your_search']
            domain = form.cleaned_data['domain']
            #match domain selected to domain id in predefined domain dictionary 
            domain_id = domain_dict[domain]
            #call the search method to see if a match exists
            result = search_list(domain_id, search_value)
            #chack the length of the list returned
            total = len(result)
            context = {'total': total, 'domain_id': domain_id, 'accounts_list': result}
            #pass on context to appropriate template
            return render(request, 'cloudstack/domain.html', context)
            

    # if a GET (or any other method) create a blank form
    else:
        #create a form object
        form = SearchForm()
    #pass form object to the template for rendering
    return render(request, 'cloudstack/search.html', {'form': form})

#view that returns a list of all VMs in a particular domain
@login_required
def list_VMs(request, domain_id):
    #prepare and make API calls
    query = {'domainid':domain_id }
    result = api.listVirtualMachines(query)
    
    #catch exception if there are no VMs in the domain
    try:
     #extract list of VMs as well as number of VMs in the domain
     VM_list = result['virtualmachine']
     total = result['count']
    
     #sort the list alphabetically by VM name
     VM_list = sorted(VM_list, key=lambda VM: VM['displayname'].lower()) 
     context = {'VM_list': VM_list, 'total': total}
     #pass on template info to context for rendering
     return render(request, 'cloudstack/list_VMs.html', context)

    except Exception:
    #if there are no VMs set total to 0
     total = 0

     context = {'total': total}

     #pass context info to template for rendering
     return render(request, 'cloudstack/list_VMs.html', context)

cloudstack/templates/cloudstack/VM.html
{% extends "cloudstack/base.html" %}
{% load mathfilters %}

{% block header %}
   <h1>VM Details - {{ virtual_machine.displayname|lower }}</h1>
{% endblock header %}

{% block content %}

 <table width=100%>
        <tr>
          <th>
            Memory
          </th>
          <th>
             vCPUs
          </th>
          <th>
             OS
          </th>
          <th>
             IP
          </th>
          <th>
             Extra IPs
          </th>
          <th>
             Disk
          </th>
       </tr>
        <tr>
           <td>
             {{ virtual_machine.memory|div:1024 }} GB
           </td>
           <td>
             {{ virtual_machine.cpunumber }} 
           </td>
          <td>
             {{ virtual_machine.templatename }}
         </td>
          <td>
             {{ virtual_machine.nic.0.ipaddress }}
         </td>
          <td>
             {{ virtual_machine.nic.0.secondaryip|length }}
         </td>
          <td>
          {% for volume in volumes_list %}
	  
	  {% ifequal "ROOT" volume.type %}
            ROOT - {{ volume.size|div:1073741824 }} GB
	  {% else %}
	    DATA - {{ volume.size|div:1073741824 }} GB 
         {% endifequal %}
         ||
	 {% endfor %}
         </td>
     </tr>
 </table>

<h5><a href="{% url 'cloudstack:domains' %}">Back to Domains</a></h5>
{% endblock content %}

cloudstack/templates/cloudstack/account.html
{% extends "cloudstack/base.html" %}
{% load mathfilters %}

{% block header %}
   <h1>Account VMs - {{ account|lower }}</h1>
{% endblock header %}

{% block content %}
{% if total %}
 <table width=100%>
        <tr>
          <th>
             VM Name
          </th>
          <th>
             VM State
          </th>
          <th>
             Created
          </th>
          <th>
             IP
          </th>
       </tr>
    {% for VM in VMs_list %}
        <tr>
           <th>
             <a href="{% url 'cloudstack:VM' domainid account VM.id %}">{{ VM.displayname|lower }}</a>
           </th>
           <td>
             {{ VM.state }} 
           </td>
          <td>
             {{ VM.created }}
         </td>
         <td>
             {{ VM.nic.0.ipaddress }}
         </td>
     </tr>
    {% endfor %}
 </table>
{% else %}
    <p>There are no VMs in this account.</p>
{% endif %}

<h5><a href="{% url 'cloudstack:domains' %}">Back to Domains</a></h5>
{% endblock content %}

cloudstack/templates/cloudstack/base.html
<!--Code customized from python Crash Course by Eric Matthes-->
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Cloudstack Online Query</title>
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>

<body>
<!-- Static navbar -->

<nav class="navbar navbar-default navbar-static-top">
<div class="container">
  
<div class="navbar-header">
   <button type="button" class="navbar-toggle collapsed"
    data-toggle="collapse" data-target="#navbar"
    aria-expanded="false" aria-controls="navbar">
   </button>
   <a class="navbar-brand" href="{% url 'cloudstack:index' %}">Home</a>
  </div>

  <div id="navbar" class="navbar-collapse collapse">
  <ul class="nav navbar-nav">
     <li><a href="{% url 'cloudstack:domains' %}">Domains</a></li>
     <li><a href="{% url 'cloudstack:latestVMs' %}">New VMs</a></li>
     <li><a href='{% url 'cloudstack:search_form' %}'>Search accounts</a></li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    {% if user.is_authenticated %}
     <li><a>Hello, {{ user.username }}.</a></li>
     <li><a href="{% url 'users:logout' %}">log out</a></li>
    {% else %}
     <!--li><a href="{% url 'users:register' %}">register</a></li-->
     <li><a href="{% url 'users:login' %}">log in</a></li>
    {% endif %}
   </ul>
  </div><!--/.nav-collapse -->
 </div>
</nav>

 <div class="container">
  <div class="page-header">
   {% block header %}{% endblock header %}
  </div>
  <div>
   {% block content %}{% endblock content %}
  </div>
 </div> <!-- /container -->
</body>
</html>

cloudstack/templates/cloudstack/domain.html
{% extends "cloudstack/base.html" %}
{% load bootstrap3 %}

{% block header %}
   <h1>Domain Accounts ( {{ total }} )</h1> 
   <h5><a href='{% url 'cloudstack:listVMs' domain_id %}'>View all domain VMs</a></h5>
{% endblock header %}

{% block content %}

{% if total %}
 <table width=70%>
        <tr>
           <th>
             Account Name
           </th>
           <th>
             Account State
           </th>
          <th>
             Total VMs
          </th>
       </tr>
    {% for account in accounts_list %}
        <tr>
           {% if account.vmtotal %}
           <th>
             <a href="{% url 'cloudstack:account' domain_id account.name %}">{{ account.name|lower }}</a>
           </th>
           {% else %}
           <th>
             {{ account.name|lower }}
           </th>
           {% endif %}
           <td>
             {{ account.state }}
           </td>
          <td>
             {{ account.vmtotal }}
         </td>
     </tr>
    {% endfor %}
 </table>
{% else %}
    <p>There are no accounts.</p>
{% endif %}

<h5><a href="{% url 'cloudstack:domains' %}">Back to Domains</a></h5>
{% endblock content %}

cloudstack/templates/cloudstack/domains.html
{% extends "cloudstack/base.html" %}

{% block header %}
   <h1>Cloudstack Domains</h1>
{% endblock header %}


{% block content %}
{% if total %}
    <ul>
    {% for domain in domains_list %}
        <li>
	<h3>
	     <a href="{% url 'cloudstack:domain' domain.id %}">{{ domain.name|lower }}</a>
        </h3>
	</li>
    {% endfor %}
    </ul>
{% else %}
    <p>There are no domains.</p>
{% endif %} 

{% endblock content %}

cloudstack/templates/cloudstack/index.html
{% extends "cloudstack/base.html" %}

{% block header %}
 <div class='jumbotron'>
  <h1>Track VMs on Cloudstack</h1>
 </div>
{% endblock header %}

{% block content %}
	<h2> Welcome to the Cloudstack Query Manager</h2>
	<!--h2>
	 <a href="{% url 'users:register' %}">Register an account</a> to make cloudstack queries!
	</h2-->
	<h3> <a href="{% url 'users:login' %}">Log in to make queries</a> <h3>
{% endblock content %}

cloudstack/templates/cloudstack/latest_VMs.html
{% extends "cloudstack/base.html" %}
{% load mathfilters %}

{% block header %}
   <h1>New VMs - {{ total }} (past week)</h1>
   <h5><a href="{% url 'cloudstack:monthVMs' %}">View VMs created in the past month</a></h5>
{% endblock header %}

{% block content %}
{% if total %}
 <table width=100%>
        <tr>
          <th>
             VM Name
          </th>
          <th>
             Account
          </th>
          <th>
             VM State
          </th>
          <th>
             Created
          </th>
          <th>
             IP
          </th>
       </tr>
    {% for VM in latest_list %}
        <tr>
           <td>
             <b><a href="{% url 'cloudstack:VM' VM.domainid VM.account VM.id %}">{{ VM.displayname|lower }}</a></b>
           </td>
           <td>
             {{ VM.account }}
           </td>
           <td>
             {{ VM.state }} 
           </td>
          <td>
             {{ VM.created }}
         </td>
         <td>
             {{ VM.nic.0.ipaddress }}
         </td>
     </tr>
    {% endfor %}
 </table>
{% else %}
    <p>There are no new VMs.</p>
{% endif %}

<h5><a href="{% url 'cloudstack:domains' %}">Back to Domains</a></h5>
{% endblock content %}

cloudstack/templates/cloudstack/list_VMs.html
{% extends "cloudstack/base.html" %}
{% load mathfilters %}

{% block header %}
   <h1>Domain VMs</h1>
{% endblock header %}

{% block content %}
{% if total %}
 <table width=100%>
        <tr>
          <th>
             VM Name
          </th>
          <th>
             Account
          </th>
          <th>
             VM State
          </th>
          <th>
             Created
          </th>
          <th>
             IP
          </th>
       </tr>
    {% for VM in VM_list %}
        <tr>
           <td>
             <b><a href="{% url 'cloudstack:VM' VM.domainid VM.account VM.id %}">{{ VM.displayname|lower }}</a></b>
           </td>
           <td>
             {{ VM.account }}
           </td>
           <td>
             {{ VM.state }} 
           </td>
          <td>
             {{ VM.created }}
         </td>
         <td>
             {{ VM.nic.0.ipaddress }}
         </td>
     </tr>
    {% endfor %}
 </table>
{% else %}
    <p>There are no VMs in this domain.</p>
{% endif %}

<h3><a href="{% url 'cloudstack:domains' %}">Back to Domains</a></h3>
{% endblock content %}

cloudstack/templates/cloudstack/month_VMs.html
{% extends "cloudstack/base.html" %}
{% load mathfilters %}

{% block header %}
   <h1>New VMs - {{ total }} (one month)</h1>
{% endblock header %}

{% block content %}
{% if total %}
 <table width=100%>
        <tr>
          <th>
             VM Name
          </th>
          <th>
             Account
          </th>
          <th>
             VM State
          </th>
          <th>
             Created
          </th>
          <th>
             IP
          </th>
       </tr>
    {% for VM in latest_list %}
        <tr>
           <td>
             <b><a href="{% url 'cloudstack:VM' VM.domainid VM.account VM.id %}">{{ VM.displayname|lower }}</a></b>
           </td>
           <td>
             {{ VM.account }}
           </td>
           <td>
             {{ VM.state }} 
           </td>
          <td>
             {{ VM.created }}
         </td>
         <td>
             {{ VM.nic.0.ipaddress }}
         </td>
     </tr>
    {% endfor %}
 </table>
{% else %}
    <p>There are no new VMs this month.</p>
{% endif %}

<h5><a href="{% url 'cloudstack:domains' %}">Back to Domains</a></h5>
{% endblock content %}

cloudstack/templates/cloudstack/search.html
{% extends "cloudstack/base.html" %}

{% load bootstrap3 %}

{% block header %}
 <h3> Search </h3>
{% endblock header %}


{% block content %}

<form method="post" action="{% url 'cloudstack:search_form' %}" class="form">
{% csrf_token %}
{% bootstrap_form form %}

{% buttons %}
  <button name="submit" class="btn btn-primary">Search</button>
{% endbuttons %}

</form>

{% endblock content %}